### ISSUE TITLE
Control box design

### ISSUE THREAD

**Issue by peterantypas** [peterantypas/ais_transponder#17]
I'm going to leave this ticket open as a discussion forum around the control box. This is the unit on the opposite end of the transponder cable. It's not a strict requirement for the transponder to operate, but I have found mine useful over the past 2 years.

I started by designing custom cutouts in a Hammond enclosure and 3D printing it. I expect this process to take a few iterations over a couple of months.

![Screenshot from 2020-11-21 15-19-58](https://user-images.githubusercontent.com/1565933/99889826-a935bb80-2c0d-11eb-9e4f-b2b5a80609c9.png)

I don't intend to make this an IP6x rated enclosure. This unit is supposed to be inside the boat cabin or some other "mostly dry" environment.

The current design features an on/off latching switch, 4 status LEDs, a transmit on/off switch, and plain wire interfaces for 12V input and NMEA+/NMEA- outputs as well as USB. It only works with the Cat5 cable option. To support the 4-wire option, it will need a basic MCU to intercept and interpret NMEA messages, as well as different cutouts, so I will probably end up with two variants.

**Comment by kagouraki** [comment]
Hello ! 
I am a cnc machinist, an electronics hobbyst and a sailor. 
I am very interested in your project ! 
If i can help with design and manufacture of the control box just tell me !

**Comment by peterantypas** [comment]
Thanks, I'll keep this in mind. Once I have the design down, maybe you can help me machine the cutouts in the stock enclosures. The stock box is very cheap (under $3), but Hammond wants quite a bit of money per unit to CNC those cutouts.

**Comment by kagouraki** [comment]
I will be glad to help ! Just say the word !
