### ISSUE TITLE
No kit at tindie.com

### ISSUE THREAD

**Issue by CarCode** [peterantypas/ais_transponder#18]
I cannot find the announced kit at tindie.com

**Comment by peterantypas** [comment]
The kit is not available yet. There's a lot of work to be done still. I expect it to be ready by next March.

**Comment by lbn52** [comment]
Great project. Do you have any ideas about the price?

**Comment by tobixen** [comment]
I'd suggest to make it more clear in the README that the kit on tindie.com is work in progress.  Well, I guess I should have intepreted "I am going to make it" as "it's not yet ready", but still I wasted time searching for it at tindie.com :-)

**Comment by peterantypas** [comment]
Done ;)
