### ISSUE TITLE
Amazing project, but where to get (odd) components

### ISSUE THREAD

**Issue by GunnarHolm** [peterantypas/ais_transponder#4]
Hi !
This looks like a nice winter project to get going before the boating season starts again next summer.
But there are some unusual components that seems difficult and expensive to source one bye one from different ebay shops. Do you have any plans to sell kits with empty PCBs and the STM32F302, Silicon Labs 4463, GlobalTop  LadyBird, NXP BGA2869 and the Skyworks 66100 ? 
Best regards,
Gunnar Holm (Stockholm Sweden)

**Comment by peterantypas** [comment]
Generally these components are available from DigiKey. The GPS module is still being sold by Adafruit, I believe.
