### ISSUE TITLE
Board availability

### ISSUE THREAD

**Issue by jimarcher** [peterantypas/ais_transponder#7]
This project looks fantastic! I have ordered boards and reflowed them in my toaster over (now dedicated to board reflow) but these components may be too fine pitch for me to do that. How are you guys making your boards for this project?

Thanks...

**Comment by junkt1** [comment]
Where did you order the kit?

**Comment by rszemeti** [comment]
Reflow was not a problem, but you need a GOOD stencil to make the paste print, and check the print before you start placing components.   Worked fine for me, no problems so far with the assembly.
