### ISSUE TITLE
AIS preamble

### ISSUE THREAD

**Issue by SamSamKhan** [peterantypas/ais_transponder#9]
Dear Peter,
You have set the PREAMBLE_CONFIG to 0x21 in radio_config_ph.h file which put the si446x to standard preamble mode. whereas the AIS standard requires NRZI coding which led to non standard preamble pattern. could you please explain why?
thanks in advance,
Saman

**Comment by peterantypas** [comment]
To the best of my recollection it didn't matter. The SYNC WORD is what the receiver keyed on, and that's set for the NRZI-encoded preamble: 001100110011, etc.
